// svelte/src/App.svelte
<script>
	import { todos, addTodo, toggleTodo } from './todos';
	export let inputText;

</script>

<main>
	<h1>Svelte를 사용한 Todo App 코드 입니다.</h1>
	<div class="input-form">
		<button on:click={() => {
			addTodo(inputText);
			inputText = '';
		}}>add</button>
		<input type="text" bind:value={inputText} on:keydown={(e) => {
			if (e.key === 'Enter' && inputText.length > 0) {
				addTodo(inputText)
				inputText = '';
			}
		}}/>
	</div>
	<ol>
		{#each $todos as todo, index }
			<li on:click|preventDefault={() => toggleTodo(index)}>
				<label for={todo.id} class={todo.completed ? "completed" : ""} >
					<input type="checkbox" id={todo.id} checked={todo.completed}/> {todo.content}
				</label>
			</li>
		{/each}
	</ol>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	.input-form {
		display: flex;
		justify-content: center;
	}

	ol {
		max-width: 400px;
		list-style: disc;
		margin: 20px auto 0 auto;
		text-align: left;
	}

	li + li {
		margin-top: 6px;
	}

	label.completed {
		text-decoration: line-through;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 2em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>

// react-mobx/src/App.tsx
import React from "react";
import { observer } from "mobx-react-lite";
import stores from "./stores";
import "./App.css";

function App() {
  const { todayStore } = stores;
  const inputRef = React.useRef<HTMLInputElement>(null);
  const addButtonRef = React.useRef<HTMLButtonElement>(null);

  return (
    <div className="App">
      <header className="App-Header">
        React + Mobx를 사용한 Todo App 코드 입니다.
      </header>
      <main>
        <h1>Today</h1>
        <div>
          <button
            ref={addButtonRef}
            onClick={() => {
              if (inputRef.current) {
                todayStore.addTodo({
                  createdAt: new Date().toISOString(),
                  content: inputRef.current.value,
                });
                inputRef.current.value = "";
              }
            }}
          >
            add
          </button>
          <input
            ref={inputRef}
            type="text"
            onKeyDown={(e) => {
              if (e.key === "Enter" && addButtonRef.current) {
                addButtonRef.current.click();
              }
            }}
          />
        </div>
        {todayStore && (
          <ol className="TODO-List">
            {todayStore.todos.map(({ content, id, completed }) => (
              <li key={id!}>
                <input
                  type="checkbox"
                  id={id}
                  checked={completed}
                  onChange={(e) => {
                    todayStore.toggleDone(id!);
                  }}
                />
                <label htmlFor={id}>
                  {completed ? <del>{content}</del> : content}
                </label>
              </li>
            ))}
          </ol>
        )}
      </main>
    </div>
  );
}

export default observer(App);
